ALTER TABLE festival
  ADD COLUMN date VARCHAR,
  DROP COLUMN start_date RESTRICT,
  DROP COLUMN end_date RESTRICT,
  DROP COLUMN location RESTRICT,
  ADD COLUMN location VARCHAR,
  DROP COLUMN country RESTRICT,
  DROP COLUMN state RESTRICT,
  DROP COLUMN city RESTRICT;
